name: crud_flutter
description: "A Flutter project for managing pelanggan data using a CodeIgniter backend."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  device_preview: ^1.2.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for clean coding practices
  flutter_lints: ^4.0.0

  # Flutter Launcher Icons: Untuk mengatur icon aplikasi (opsional)
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
